pullRequests.grouping = [ { name = "all", "filter" = [{"group" = "*"}]} ]
updates.pin = [
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "2.13.18" }
  { groupId = "org.scala-lang", artifactId = "scala-compiler", version = "2.13.18" }
  { groupId = "org.scala-lang", artifactId = "scala-reflect", version = "2.13.18" }
]
